import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Wrapper } from '@/components/styled/layout'
import '@/styles/tailwind.css'
import '@/styles/root.css'
import '@/styles/global.css'
import '@/styles/notion.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  )
}
